POST http://localhost:5243/api/v1/Items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZWIwZGU0NDMtMTRhZi00OTczLTk2MTYtN2RkNjg3M2ZhNWQ1IiwibmJmIjoxNjgzODg4NzY2LCJleHAiOjE2ODM4ODg3NzEsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTI0MyIsImF1ZCI6InlvdV9oZWhlIn0.7ki20375ADbH3qKNJaiHCcKVh3LVV1v9GPZuoEiiLi0

{
    "Name": "Hehehehheeh"
}

