DELETE  http://localhost:5243/api/v1/Items/be572997-22cc-4824-9c01-72c1dad9f8ee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZWIwZGU0NDMtMTRhZi00OTczLTk2MTYtN2RkNjg3M2ZhNWQ1IiwibmJmIjoxNjgzNzUwNTM1LCJleHAiOjE2ODM3NTA1NjUsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTI0MyIsImF1ZCI6InlvdV9oZWhlIn0.5_lUHX33hmc7yHYVl2zYmDrV6BjqYLHHt_3OeaTMLxI 