// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230510112955_DbInit")]
    partial class DbInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.Entities.Items", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4c16563-108b-484f-9a70-30a322395f27"),
                            CreatedAt = new DateTime(2023, 5, 10, 11, 29, 55, 608, DateTimeKind.Utc).AddTicks(6933),
                            Name = "Item1",
                            UpdatedAt = new DateTime(2023, 5, 10, 11, 29, 55, 608, DateTimeKind.Utc).AddTicks(6934),
                            UserId = new Guid("eb0de443-14af-4973-9616-7dd6873fa5d5")
                        },
                        new
                        {
                            Id = new Guid("782d9fda-8eea-43d9-b2f7-428e3740defe"),
                            CreatedAt = new DateTime(2023, 5, 10, 11, 29, 55, 608, DateTimeKind.Utc).AddTicks(6954),
                            Name = "Item2",
                            UpdatedAt = new DateTime(2023, 5, 10, 11, 29, 55, 608, DateTimeKind.Utc).AddTicks(6955),
                            UserId = new Guid("eb0de443-14af-4973-9616-7dd6873fa5d5")
                        });
                });

            modelBuilder.Entity("server.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb0de443-14af-4973-9616-7dd6873fa5d5"),
                            CreatedAt = new DateTime(2023, 5, 10, 11, 29, 55, 608, DateTimeKind.Utc).AddTicks(6313),
                            Password = "24C0A769D8746A0A0D5B1F06EDC6A3BE6EFF378004694DC86EB3E4DA7DCF0750C9EA2F5D0BAF2C4C9F350F202A456595707AD4733BC86EC8FAE933221566BBB6",
                            UpdatedAt = new DateTime(2023, 5, 10, 11, 29, 55, 608, DateTimeKind.Utc).AddTicks(6314),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("server.Entities.Items", b =>
                {
                    b.HasOne("server.Entities.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Entities.User", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
